### ISSUE TITLE
A Problem of Perms

### ISSUE THREAD

**Issue by YZhang-Jeremy** [games647/CommandForward#1]
Hey can u plz add something as forward the command to the bc and run as a OP or something? Because I want to use this plugin to work with my BC punishment plugin and my anti cheat plugin and I want to use this to ban people. Thx XD

**Comment by TuxCoding** [comment]
You mean if the command sender is either the console or a player with op permission it should be executed with OP permissions on the bungee server?

**Comment by YZhang-Jeremy** [comment]
yes

**Comment by YZhang-Jeremy** [comment]
I especially need the command which is executed by a console can be executed with OP perms in BC

**Comment by YZhang-Jeremy** [comment]
can u do this? XD

**Comment by TuxCoding** [comment]
Yes

**Comment by YZhang-Jeremy** [comment]
k how long can u do this plz?
becuase my anti cheat can not ban hackers now this is so bad
thx very much XD

**Comment by YZhang-Jeremy** [comment]
excuse me? Can u plz fix this? Because my anti-cheat plugin can not ban hackers now and i think it is gonna be easy for u to do that. Thanks!!
XD
