### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by P1otrulla** [games647/CommandForward#17]
When i install and use command forward i have this error on bungee console: https://pastebin.com/wpRERWvg

**Comment by TuxCoding** [comment]
This got fixed a while back by #9 . Which version of the plugin do you run?

**Comment by P1otrulla** [comment]
I download latest from GitHub

**Comment by TuxCoding** [comment]
Likely 0.3.X. The version on spigot is newer then.

**Comment by P1otrulla** [comment]
Ah okey my bad, Thanks!
