### ISSUE TITLE
Other plugins commands dont work

### ISSUE THREAD

**Issue by ItzRonaldMLG** [games647/CommandForward#26]
Hello,
I cant seem to execute bungeecord commands from other plugins as the player itself.
Like i have TAB plugin on only bungeecord, but i cant seem to execute ''/sb toggle'' as the player.
Executed from PaperSpigot console:
https://i.imgur.com/lwLryKL.png
output:
https://i.imgur.com/1YdneZc.png

**Comment by TuxCoding** [comment]
It could be an alias and only the original commands do work. Could post the plugin name or the registration process if you have the source code?

**Comment by ItzRonaldMLG** [comment]
Thank you for the fast response.
This is the plugin, i dont know what registration process is used or what you mean by this.
I only know that even the main command from that plugin does not work.
TAB: https://polymart.org/resource/tab-1-5-x-1-19-4.484

But for example BungeeOnlineTime (also a bungeecord plugin) does.
But if i use a space in the command it only shows i put the first argument in
''/sb toggle'' -> ''Unknown command sb''

**Comment by TuxCoding** [comment]
According to the free version of the plugin, the bungeecord command is actually `btab`. 

Furthermore, the `scoreboard` is a Spigot vanilla command, so it's not available in BungeeCord. This plugin performs the command on the proxy instance, so there scoreboard functionality available.

**Comment by ItzRonaldMLG** [comment]
This command doesnt need the btab infron of it normaly, but i will try this.
The premium version from TAB plugin has a scoreboard, thats why i use /sb toggle, it is a command form the TAB plugin to toggle the scoreboard on/off

**Comment by TuxCoding** [comment]
Okay I found the source of this bug. The plugin has a weird approach about command execution. Instead of registering the command on startup, it executes it dynamically when watching the chat. It should be fixed now. 

https://ci.codemc.io/job/Games647/

**Comment by ItzRonaldMLG** [comment]
It doesnt seem to work, you said something about monitoring the chat?
Im trying this from the console, because im using it in a GUI from DeluxeMenus. It cant execute bungeecord commands.

**Comment by TuxCoding** [comment]
Could you run the newest build? I changed the method to include the invoking user, which seems to necessary for the plugin.
